package io.bootify.ticket_app.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;


@Entity
@Table(name = "Admins")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
public class Admin {

    // Specifies that the primary key is auto-generated by the database using an identity column.
    @Id
    @Column(nullable = false, updatable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Maps this field to a non-nullable column in the database.
    @Column(nullable = false)
    private String name;

    // Ensures the column is not null and cannot be updated after the entity is created.
    @CreatedDate
    @Column(nullable = false, updatable = false)
    private OffsetDateTime dateCreated;

    // Ensures the column is not null.
    @LastModifiedDate
    @Column(nullable = false)
    private OffsetDateTime lastUpdated;

}
