package io.bootify.ticket_app.domain;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Flag {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // Specifies that the primary key is auto-generated by the database using an identity column.
    private Long id;

    // Field to store the status of the flag, typically used as a flagging mechanism or status indicator.
    private  Integer status;
}
