package io.bootify.ticket_app.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import java.time.OffsetDateTime;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;


@Entity
@Table(name = "Tickets")
@EntityListeners(AuditingEntityListener.class)
@NoArgsConstructor
@Getter
@Setter
public class Ticket {
    //Constructor to initialize Ticket with specific Vendor, Customer, and count.
    public Ticket(Vendor vendorId, Customer customerId, Integer count) {
        this.vendorId = vendorId;
        this.customerId = customerId;
        this.count = count;
    }

    // Specifies that the primary key is auto-generated by the database using an identity column.
    @Id
    @Column(nullable = false, updatable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Specifies the foreign key column in the "Tickets" table for the Vendor entity.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vendor_id")
    private Vendor vendorId;

    // Specifies the foreign key column in the "Tickets" table for the Customer entity.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id")
    private Customer customerId;

    // The number of tickets associated with this entity.
    @Column
    private Integer count;

    // Timestamp of when the ticket was created.
    @CreatedDate
    @Column(nullable = false, updatable = false)
    private OffsetDateTime dateCreated;

    // Timestamp of the last update to the ticket record.
    @LastModifiedDate
    @Column(nullable = false)
    private OffsetDateTime lastUpdated;
}
